version: '3'

services:
  app:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    # Enable hot reload
    command: npm run dev
